version: "3.4"

networks:
  nuremberg_api-dev:
    driver: bridge

services:
  nuremberg_api:
    image: nuremberg:latest
    depends_on:
      - "postgres_database"
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:80"

  postgres_database:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "loki74"
      POSTGRES_DB: "NurembergDb"

volumes:
  db_volume: